#!/bin/bash

ROOT=$(dirname $(realpath $0))

NAME=dbuild

set -e 

if [[ $(docker ps) =~ $NAME ]] ; then
    
    docker stop $NAME
fi


if [[ $(docker ps -a) =~ $NAME ]] ; then
    
    docker rm $NAME
fi 

cd $ROOT

docker build -t $NAME .

docker run -ti -d --name $NAME \
    -e UID=1000 -e GID=1000 \
    -e DISPLAY \
    -v ~/.ssh:/home/jf/.ssh \
    -v ~/.gitconfig:/home/jf/.gitconfig \
    -v /home/jf/git/20-os:/home/jf/git/20-os \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    --restart unless-stopped \
$NAME